version: '3.7'

services:
  flagr:
    image: ghcr.io/openflagr/flagr:latest
    container_name: flagr
    ports:
      - "18000:18000"
    environment:
      - FLAGR_DB_DRIVER=sqlite3
      - FLAGR_DB_DSN=/data/flagr.sqlite3
      - FLAGR_BASIC_AUTH_ENABLED=true
      - FLAGR_BASIC_AUTH_USERNAME=admin
      - FLAGR_BASIC_AUTH_PASSWORD=senha_super_segura
      - FLAGR_UI_APP_NAME=Flagr - Vexilla
      - FLAGR_UI_PRIMARY_COLOR=#1565c0

    volumes:
      - ./data:/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4318:4318"